appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: RXcLzOWcADKSYN25aeM1zrlE64dgrYF/e3jRxKSm1sCJVDkyF8hsr3R2fmNYScA9EWaRysxR/1hwx0Z5DaRBhu/MdUp+ip31katnyr6aLk+EUu4I3wv4hoUe+jlNzDEBEQhfwiD7LVLxzAOvAdUv2+QMKygokM7ijn9+ZNRC2iPZHWFKHtCmJ12Q5vUB48bcFVrgg7BlmfIJcARsMilUnKT2GdzYsXC7SnJ4Pf6V5Kjs8xfv98noeMQAy5Ps7mASa453tTzki9dOjRfc+cJ+BwuReyQ5iQ2PTJstfJU4czHsKxmT+k4EqwTHoD2CEiLg9dAv9gJvmL6qz1Lb5Cy4zALQvzK6FcLLZJvchPQTcv2v2NyvhJYpI+ArXWkRe4/2hKBQY5+IMwAekqlatOVDssfzNEnTonm1i2K+F9ElKORF+hAU77iGL/MkMoTQW2p+RyTOe7Sd18Y6NLsbhZWkG8ia5bRT7liKmVow/t+NV52nc0DxUEwaKTRHyS8raixHd6GbZMWANDdtkAwDDWa8EOfnTCirpJz10vgAyKcZElUSygXWJiUVv6ZBDF4uAIOFCNR2Hph9YrVMVPKpFKW1YSp0qchfPTzHmVJkpciib3CQWxytrCFzpqzkzZsWg/EPAt4ELpgy6kKyfyDsI43Yn3UU4uMfxVDLztzOQ92fQ7g=}
